email:
  fromEmail: admin@yahoo.com
  fromName: jquery-alternative-demo
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  8d6af961-64b6-4e9f-b086-91639ac6233e:
    name: Common
siteGroups:
  1400f314-aced-4092-9772-81054a2ec6a7:
    name: jquery-alternative-demo
sites:
  1693f771-58b7-42a3-91c7-467d2273f6d6:
    baseUrl: $DEFAULT_SITE_URL
    handle: default
    hasUrls: true
    language: en-US
    name: jquery-alternative-demo
    primary: true
    siteGroup: 1400f314-aced-4092-9772-81054a2ec6a7
    sortOrder: 1
system:
  edition: solo
  name: jquery-alternative-demo
  live: true
  schemaVersion: 3.3.3
  timeZone: America/Los_Angeles
users:
  requireEmailVerification: true
  allowPublicRegistration: false
  defaultGroup: null
  photoVolumeUid: null
  photoSubpath: ''
